//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportApp.Helpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planes
    {
        public int PlaneID { get; set; }
        public int PlaneNumber { get; set; }
        public int PlanePlaces { get; set; }
        public int PlaneSpeed { get; set; }
        public int PlaneDeparture { get; set; }
        public int PlaneArrival { get; set; }
        public int PlaneDistance { get; set; }
        public int PlaneSellPlaces { get; set; }
    
        public virtual Airports Airports { get; set; }
        public virtual Airports Airports1 { get; set; }
    }
}
